version: '3.1'
services:
  database:
    image: postgres:16.2-alpine3.19
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=clinic
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - PGDATA=/var/lib/postgresql/data/application
    volumes:
      - ../../../data:/var/lib/postgresql/data/application
  pgadmin:
    image: dpage/pgadmin4:8.3
    ports:
      - "8000:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=joanna.z.jaroszewska@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin

